<div id="navbar" class="navbar-collapse collapse">
    <form class="navbar-form navbar-right" method="post" action="login">
        <div class="form-group">
            <input type="text" name="email" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
            <input type="password" name="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
    </form>
</div>