<div class="row center-block">
    <div class="col-md-6 col-md-offset-3">
        <form class="form-horizontal" method="post" action="submit_registration">
            <h2 align="center">Register</h2>

            <div class="form-group">
                <label for="name" class="col-md-3 control-label">Username</label>

                <div class="col-md-7">
                    <input type="text" name="username" class="form-control" id="name" placeholder="name">
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-3 control-label">Email address</label>

                <div class="col-md-7">
                    <input type="email" name="email" class="form-control" id="email" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-3 control-label">Password</label>

                <div class="col-md-7">
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <label for="confirm_password" class="col-md-3 control-label">Confirm Password</label>

                <div class="col-md-7">
                    <input type="password" name="confirm_password" class="form-control" id="confirm_password" placeholder="Confirm Password">
                </div>
            </div>
            <div class="form-group">
                <div align="center" class="checkbox">
                    <label>
                        <input type="checkbox"> Remember Me
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary center-block">Register</button>
        </form>
    </div>
</div>